version: '3.9'
services:
  aws-cli-container:
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: aws-cli/Dockerfile
    container_name: awscli-container
    volumes:
      - .:/workdir
    env_file:
      - .env
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json
  