version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stackies-sam-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hh0asjglf3w8"
s3_prefix = "stackies-sam-api"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
