AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dva-01-001
  Sample SAM Template for dva-01-001

Globals:
  Function:
    Timeout: 10

Resources:
  PostMemberFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.post_handler
      Role: !GetAtt PostMemberFunctionRole.Arn
      Runtime: python3.9
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /members
            Method: post
  GetMemberFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: member-get/src/
      Handler: app.get_handler
      Role: !GetAtt PostMemberFunctionRole.Arn
      Runtime: python3.9
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /members
            Method: get
  PostMemberFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: PostMemberFunctionPolicies
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:List*
                  - dynamodb:DescribeReservedCapacity*
                  - dynamodb:DescribeLimits
                  - dynamodb:DescribeTimeToLive
                Resource: "*"
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:Scan
                Resource: !GetAtt Table.Arn
            
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: name
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: name
          KeyType: HASH
      TableName: members